[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.9"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.9"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.12.9"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.9"

[[constraint]]
  name = "github.com/cppforlife/go-patch"
  revision = "90228d47281247384683e5fded0f15afa3e5d29a"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[prune.project]]
  name = "k8s.io/code-generator"
  unused-packages = false
  non-go = false
